# Generated by Django 5.2.5 on 2025-08-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_assignees_alter_task_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "Urgent"),
                    ("High Priority", "High Priority"),
                    ("Medium Priority", "Medium Priority"),
                    ("Low Priority", "Low Priority"),
                    ("Optional", "Optional"),
                ],
                default="Medium Priority",
                max_length=50,
            ),
        ),
    ]
