# Generated by Django 5.2.5 on 2025-08-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_worker_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["username"],
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
            },
        ),
    ]
